// Espejo 1:1 de api-pos/src/constants/categorias.constants.ts (SPEC-020, api-pos).
export const CATEGORIA_ERRORS = {
  NOT_FOUND: 'ERR_CATEGORIA_NOT_FOUND',
  NOMBRE_DUPLICADO: 'ERR_CATEGORIA_NOMBRE_DUPLICADO',
  PADRE_NOT_FOUND: 'ERR_CATEGORIA_PADRE_NOT_FOUND',
  JERARQUIA_EXCEDIDA: 'ERR_CATEGORIA_JERARQUIA_EXCEDIDA',
  PADRE_INVALIDO: 'ERR_CATEGORIA_PADRE_INVALIDO',
  CON_SUBCATEGORIAS_ACTIVAS: 'ERR_CATEGORIA_CON_SUBCATEGORIAS_ACTIVAS',
  CON_PRODUCTOS_ASOCIADOS: 'ERR_CATEGORIA_CON_PRODUCTOS_ASOCIADOS',
  CONFIRMACION_REQUERIDA: 'ERR_CATEGORIA_CONFIRMACION_REQUERIDA',
} as const;

// Códigos de negocio (409/404 sin `details` de Zod) que corresponden a un campo visible del
// formulario de registro rápido (nombre, padreId) — mismo criterio que PRODUCTO_ERROR_CODE_TO_FIELD.
export const CATEGORIA_ERROR_CODE_TO_FIELD: Record<string, string> = {
  [CATEGORIA_ERRORS.NOMBRE_DUPLICADO]: 'nombre',
  [CATEGORIA_ERRORS.PADRE_NOT_FOUND]: 'padreId',
  [CATEGORIA_ERRORS.JERARQUIA_EXCEDIDA]: 'padreId',
  [CATEGORIA_ERRORS.PADRE_INVALIDO]: 'padreId',
};

export const CATEGORIA_ROLES_ESCRITURA = ['superadmin', 'admin'] as const;
